### ISSUE TITLE
Trabajo duplicado

### ISSUE THREAD

**Issue by jorgesumle** [davidam/libremanuals.github.io#3]
Cada vez que se modifica algo genérico se ha de hacer en cada archivo separado. Esto, además de aumentar el trabajo, hace que los parches sean más largos y tediosos y sea más complicado añadir código sin hacerlo en varios sitios a la vez.

Propongo dos soluciones:
1. Utilizar un generador de páginas como [Haunt](https://dthompson.us/projects/haunt.html) o cualquier otro que sea libre
2. Utilizar un lenguaje de programación del lado del servidor con el que podamos usar un sistema de plantillas (como Jinja2, por ejemplo).

Yo prefiero la primera opción. En ambos casos me es indiferente el lenguaje que usar mientras sea libre y sea desarrollado por una comunidad.

**Comment by davidam** [comment]
Suena bien, se pueden hacer las modificaciones con sed y es solo aplicar un comando, pero me parece bien usar Haunt, u Orgmode para eso. Si te interesa aprender eso, le dedicaría algo de tiempo yo también. La primera versión de Libremanuals era con ikiwiki ...

Saludos.
